### ISSUE TITLE
[FEATURE REQUEST]Enable/disable edit on a row level

### ISSUE THREAD

**Issue by lab220** [o2xp/react-datatable#139]
## Summary

Currently, you can set that either all rows are editable or no row is editable.
Could we have a possibility to make some rows editable and others read-only?

This could be implemented by passing a canEditRow(row) function, with the row data as a parameter.
E.g. if you only want rows with instructions in status open to be editable, you would set:
`options.canEditRow = ({insStatus}) => insStatus === 'OPEN'`

**Comment by MorganDbs** [comment]
It's an interesting feature ! We will work on it.

**Comment by MorganDbs** [comment]
Good news ! We released your request in 1.1.8, you can update your package !

Doc:

| Property | Type | Required? | Default | Description |
|:---|:---:|:---:|:---:|:---|
| features .canEditRow | (row) => boolean | no | () => true |  Giving row as parameter and expecting a boolean as result. Do determine if a row is editable or not. |

**Comment by HamidMolareza** [comment]
Please also add this feature for **delete**. 
**CanDeleteRow: (row) => boolean**
