### ISSUE TITLE
[BUG] Datatable dont render after build

### ISSUE THREAD

**Issue by tuliocll** [o2xp/react-datatable#159]
After build with npm run build or yarn build the datatable render only the message "There is no data yet, try to refresh..."
print:
![Captura de tela de 2019-09-26 16-38-47](https://user-images.githubusercontent.com/22357579/65720160-c577b000-e07d-11e9-95bd-5052e1b5ee56.png)

## Expected Behavior
Show datatable and data

## Current Behavior
Component rendering only the message "There is no data yet, try to refresh..."

## Steps to Reproduce
1.fork/download this sample https://codesandbox.io/s/body-cell-override-example-for-o2xpreact-datatable-12rof
2.install dependencies
3.build
4. run

**Comment by rchvalbo** [comment]
Any news on this?

**Comment by MorganDbs** [comment]
Sorry for delay, you can update to 1.1.27 ! @tuliocll @rchvalbo
