### ISSUE TITLE
[BUG]Not possible to place two datatables with different data on the same route

### ISSUE THREAD

**Issue by DanielSkoros** [o2xp/react-datatable#182]
[Sandbox](https://codesandbox.io/s/basic-example-o2xpreact-datatable-ulczj)

## Expected Behavior

Render two different datatables based on options prop

## Current Behavior

Renders the second datatable twice

## Possible Solution

Add an ability to rerender on a same route

**Comment by MorganDbs** [comment]
Hi, thanks for the feed back. We will try correct that asap I think it's because we are using redux in it !

**Comment by DanielSkoros** [comment]
Yes, I'm pretty sure it is because of redux

**Comment by MorganDbs** [comment]
@DanielSkoros Hey, you can update to 1.1.22, I fix that and you no longer needs to put the props ```dtKey```
