### ISSUE TITLE
[BUG] Building react-datatable does not work with Cordova

### ISSUE THREAD

**Issue by wsideveloper** [o2xp/react-datatable#186]
react-datatable does not work on cordova build.

## Expected Behavior

react-datatable should work on cordova build as per other react application.

## Current Behavior

react-datatable shows "There is no data yet, try to refresh" instead of the table.

## Steps to Reproduce

1) npm install -g react.cordova
2) reco init com.example.hello "project_name"
This creates react-app and cordova-app into the <project name> directory.
3) Place react app into <project name>/react-js/src directory.
4) cd project_name
5) reco build
6) reco cordova build
7) reco cordova run browser

## Possible Implementation

npm start
=======
![ok](https://user-images.githubusercontent.com/42828345/69214486-0bdf1c00-0ba2-11ea-8594-8e7042e93e18.png)

cordova run browser
==============
![nok](https://user-images.githubusercontent.com/42828345/69214484-0b468580-0ba2-11ea-8da2-6e911dce2a3c.png)

**Comment by MorganDbs** [comment]
Hi @wsideveloper, thanks for the feedback. I'll try to work on this case ASAP but I have other priorities right now. I'll keep you up to date !

**Comment by MorganDbs** [comment]
Well I have struggle to build with cordova (never used it) can you create a repo that I can clone and work on it please ? Would help me a lot ! @wsideveloper

**Comment by MorganDbs** [comment]
Sorry for delay, you can update to 1.1.27 ! @wsideveloper

**Comment by wsideveloper** [comment]
Thank you. Appreciate your effort.
