### ISSUE TITLE
Is it possible to edit the no-rows text?

### ISSUE THREAD

**Issue by MaartenCleenders** [o2xp/react-datatable#187]
Hi,

My application loads the data async to the page loading, every now and than the data will be loaded in a little slower if the network isn't quite as fast. When this occurs the user is prompted with the message to refresh. I would like to overwrite this to just say to hold on. 

Is this possible?

Kind regards

**Comment by MorganDbs** [comment]
Hi, I'll add something to override this text. Hitting you back when it's done

**Comment by MorganDbs** [comment]
You can update to 1.1.23 its live :)
```js
const options = {
  text: {
    noRow: "The text you want"
  },
  ...
}
```
