### ISSUE TITLE
[QUESTION] get selected data from canSelectRow property

### ISSUE THREAD

**Issue by ERFFFFF** [o2xp/react-datatable#229]
Hi, first of all, thank you for this amazing package !
I have a question, i would like to get the selected row with the ` canSelectRow: true` property but without using the `selectionIcons ` , (basically i just want to get the data of the row when i select it).
I saw that you are using in o2xp/react-datatable/blob/develop/data/optionsObjectSample.js the `rowsSelected` property but it is not used in ` features/options` (or i just don't know how to get it). please could you help me find a solution for my problem ?

Kind regards,

**Comment by MorganDbs** [comment]
Hi @ERFFFFF ! Sorry but for now i'm not providing direct access to "rowsSelected". I think it's a nice to have but unfornutatly I can't developped it yet, I have other thing in my scope but you can do a request feature !

**Comment by ERFFFFF** [comment]
Okey i will do that, thanks for the answer !
