### ISSUE TITLE
[QUESTION]  editable set the display but its not updating the value in the code

### ISSUE THREAD

**Issue by ERFFFFF** [o2xp/react-datatable#235]
Hey again :p

When i set a value to one of my cell, the value is displayed, but when i print the row with console.log, the value of my cell is not set, the value stay empty.
Is that normal ? can i get the value set in any way ? (i really need it) 

Kind regards,

**Comment by MorganDbs** [comment]
@ERFFFFF  I'm sorry but this is not possible because we had some issue with input focus loss
