### ISSUE TITLE
[QUESTION] acces canDelete button 

### ISSUE THREAD

**Issue by ERFFFFF** [o2xp/react-datatable#236]
Hey, (sorry but i have like 300 questions, please tell me if am annoying and gonna stop to question you haha)
So, when i delete a row, the display is deleted and not the row in the code, i would like to know if it was possible to have acces to this event so that i can delete it myself. (is it canDelete ?)

Kind regards,

**Comment by MorganDbs** [comment]
@ERFFFFF You can't, but can still build your own delete button with https://github.com/o2xp/react-datatable#additional-actions-props
