### ISSUE TITLE
problem on functional component

### ISSUE THREAD

**Issue by rionalab** [o2xp/react-datatable#278]
i execute the example on a functional component after loads the three rows its keep adding a blank row and not stopping,
and console give me this

index.js:1 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: MuiThemeProviderOld, ScrollSync, ScrollSyncPane, WithStyles(ButtonBase), WithStyles(IconButton), WithStyles(Input), WithStyles(Menu), WithStyles(Modal), WithStyles(Popover), WithStyles(SvgIcon), WithStyles(WithFormControlContext(InputBase)), WithStyles(WithFormControlContext(Select)), WithStyles(c)

...

index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ScrollSyncPane which is inside StrictMode. Instead, add a

index.js:1 Warning: Legacy context API has been detected within a strict-mode tree.

...

**Comment by Rutorai** [comment]
Hello,

I have the same problem. In my case, it seems to be related to an incompatibility with bootstrap.
As soon as I remove my bootstrap import, or any component than import bootstrap it works.

**Comment by MorganDbs** [comment]
Hi @rionalab,

the datatable will be re-write soon !
