### ISSUE TITLE
Warning: React.createFactory()

### ISSUE THREAD

**Issue by abdulkaderelrawas** [o2xp/react-datatable#285]
When using the data table; after rendering a warning pops up in the browser's console.

## Expected Behavior
There should be no warnings telling us that the data table will not work (`React.createFactory()` will be deprecated) in future releases.

## Current Behavior
A warning pops up saying:

`Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.`

## Possible Solution
The usage of `React.createElement()` instead of `react.createFactory()`

## Steps to Reproduce
1. `npm i @o2xp/react-datatable`
2. `import {Datatable} from "@o2xp/react-datatable";`
3. apply options for data table: `let options = {...}`
4. use data table in your app `<Datatable options={options} />;`

**Comment by MorganDbs** [comment]
Hello @abdulkaderelrawas,

We are curently working on V2 of the library, these warnings will disappear in next version :)
